version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pos-postgres
    restart: always
    environment:
      POSTGRES_DB: posdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pos_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pos-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pos.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ../pos-phase1/backend/api
    container_name: pos-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/posdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: verysecretkey
    depends_on:
      - postgres

volumes:
  pos_pgdata:
